import Image from "next/image";
import Link from "next/link";
import { ArrowDown, CheckCircle2 } from "lucide-react";
import { CTA, Projects, Services } from "@/components/sections";

export default function Home(){return <>
  <section className="hero"><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow">Reformas integrales · Madrid</span><h1>Espacios pensados para <em>vivir mejor.</em></h1><p>Diseñamos y ejecutamos reformas con una planificación clara, materiales honestos y atención a cada detalle.</p><div className="actions"><Link className="button" href="/contacto">Pedir presupuesto</Link><Link className="text-link" href="/proyectos">Ver proyectos</Link></div><div className="hero-facts"><span><strong>15+</strong>Años de experiencia</span><span><strong>120</strong>Proyectos realizados</span><span><strong>1</strong>Equipo coordinado</span></div></div><div className="hero-image"><Image src="/images/proyecto-salon.webp" alt="Reforma integral de salón y cocina" fill priority sizes="(max-width:900px) 100vw, 50vw"/><div className="image-note"><span>Proyecto destacado</span><strong>Reforma integral · Madrid</strong></div></div></div><a className="scroll" href="#servicios"><ArrowDown/>Descubrir</a></section>
  <section className="section intro"><div className="container intro-grid"><span className="eyebrow">Nuestra forma de trabajar</span><div><h2>El diseño importa. La ejecución también.</h2><p>Convertimos ideas en espacios coherentes, funcionales y duraderos. Un único equipo se ocupa de planificar, coordinar y supervisar cada fase.</p></div></div></section>
  <section className="section services-section" id="servicios"><div className="container section-heading"><span className="eyebrow">Servicios</span><h2>Todo lo necesario para transformar tu vivienda.</h2></div><div className="container"><Services/></div></section>
  <section className="process"><div className="container process-grid"><div className="process-image"><Image src="/images/proceso-reforma.webp" alt="Profesional trabajando durante una reforma" fill sizes="(max-width:900px) 100vw, 50vw"/></div><div className="process-copy"><span className="eyebrow">Un proceso sin improvisaciones</span><h2>De la primera visita a la entrega final.</h2>{[["01","Escuchamos","Visitamos el espacio y definimos necesidades, prioridades y presupuesto."],["02","Planificamos","Organizamos distribución, materiales, calendario y coordinación de gremios."],["03","Construimos","Supervisamos la obra y cuidamos los detalles hasta la entrega."]].map(([n,t,x])=><div className="step" key={n}><span>{n}</span><div><h3>{t}</h3><p>{x}</p></div></div>)}</div></div></section>
  <section className="section projects-section"><div className="container heading-row"><div><span className="eyebrow">Proyectos</span><h2>Reformas que ganan luz, orden y carácter.</h2></div><Link className="text-link" href="/proyectos">Ver todos</Link></div><div className="container"><Projects/></div></section>
  <section className="quote"><div className="container"><p>“La diferencia está en pensar bien antes de construir y cuidar igual lo que se ve y lo que queda oculto.”</p><span>Reformas Iker · Dirección de obra</span></div></section>
  <section className="section trust"><div className="container trust-grid"><div><span className="eyebrow">Compromiso</span><h2>Una reforma acompañada de principio a fin.</h2></div><div>{["Presupuesto detallado y explicado","Calendario y seguimiento de obra","Coordinación de todos los profesionales","Limpieza y revisión antes de la entrega"].map(x=><p key={x}><CheckCircle2/> {x}</p>)}</div></div></section>
  <CTA/>
</>}
