import Image from "next/image";
import Link from "next/link";
import { Bath, ChefHat, House, PaintRoller, Ruler, Wrench } from "lucide-react";

export const services=[{title:"Reformas integrales",text:"Coordinamos el proyecto completo, desde la distribución hasta los últimos acabados.",icon:House},{title:"Cocinas",text:"Diseñamos cocinas funcionales, luminosas y preparadas para el uso diario.",icon:ChefHat},{title:"Baños",text:"Renovamos instalaciones, revestimientos y equipamiento con una ejecución precisa.",icon:Bath},{title:"Albañilería",text:"Demoliciones, tabiquería, suelos y revestimientos adaptados a cada espacio.",icon:Wrench},{title:"Pintura y acabados",text:"Colores, texturas y terminaciones que dan coherencia al conjunto.",icon:PaintRoller},{title:"Diseño y distribución",text:"Estudiamos circulaciones, almacenaje y luz para aprovechar mejor cada metro.",icon:Ruler}];
export function PageHero({eyebrow,title,text}:{eyebrow:string,title:string,text:string}){return <section className="page-hero"><div className="container"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div></section>}
export function Services({all=false}:{all?:boolean}){return <div className="service-grid">{services.slice(0,all?6:3).map(({title,text,icon:Icon},i)=><article className="service-card" key={title}><span>0{i+1}</span><Icon/><h3>{title}</h3><p>{text}</p><Link href="/contacto">Consultar proyecto</Link></article>)}</div>}
export function CTA(){return <section className="cta"><div className="container"><span className="eyebrow">Hablemos de tu espacio</span><h2>Una buena reforma empieza con una conversación clara.</h2><Link className="button light" href="/contacto">Solicitar presupuesto</Link></div></section>}
export function Projects(){return <div className="project-grid"><article className="project large"><Image src="/images/proyecto-salon.webp" alt="Salón y cocina reformados con luz natural" fill sizes="(max-width:800px) 100vw, 66vw"/><div><span>Reforma integral</span><h3>Vivienda abierta a la luz</h3></div></article><article className="project"><Image src="/images/proyecto-bano.webp" alt="Baño reformado con acabados naturales" fill sizes="(max-width:800px) 100vw, 34vw"/><div><span>Baño</span><h3>Calma, piedra y madera</h3></div></article><article className="project"><Image src="/images/proceso-reforma.webp" alt="Instalación de revestimiento de madera durante una reforma" fill sizes="(max-width:800px) 100vw, 34vw"/><div><span>Proceso</span><h3>Precisión en cada encuentro</h3></div></article></div>}
